### ISSUE TITLE
Given address is not a valid Ethereum address

### ISSUE THREAD

**Issue by chriscrutt** [ivorytowerdds/harmonauts#15]
to recreate:
```
$ cd
$ git clone https://github.com/ivorytowerdds/harmonauts.git
$ cd harmonauts
$ npm install
$ npm audit fix
```
create `.env` file and paste
```
//MAINNET
//Account: ONE address
MAINNET_PRIVATE_KEY=[PRIVATE KEY]
MAINNET_MNEMONIC=[MNEMONIC]
MAINNET_0_URL='https://api.s0.t.hmny.io'

GAS_LIMIT=9321900
GAS_PRICE=1000000000
```
replace `[PRIVATE KEY]` with private key
replace `[MNEMONIC]` with mnemonic phrase
```
$ truffle compile
$ truffle migrate --network mainnet --reset
```
and receive:
```
Compiling your contracts...
===========================
> Everything is up to date, there is nothing to compile.

Error: Given address "one1gh043zc95e6mtutwy5a2zhvsxv7lnlklkj42ux" is not a valid Ethereum address.
    at Object.toChecksumAddress (/usr/local/lib/node_modules/truffle/build/webpack:/node_modules/web3-utils/src/index.js:300:1)
    at Method.outputBlockFormatter (/usr/local/lib/node_modules/truffle/build/webpack:/node_modules/web3-core-helpers/src/formatters.js:322:1)
    at Method.web3.eth.getBlock.method.outputFormatter (/usr/local/lib/node_modules/truffle/build/webpack:/packages/interface-adapter/dist/shim/overloads/ethereum.js:38:1)
    at Method.formatOutput (/usr/local/lib/node_modules/truffle/build/webpack:/node_modules/web3-eth/node_modules/web3-core-method/src/index.js:169:1)
    at sendTxCallback (/usr/local/lib/node_modules/truffle/build/webpack:/node_modules/web3-eth/node_modules/web3-core-method/src/index.js:640:1)
    at /usr/local/lib/node_modules/truffle/build/webpack:/node_modules/web3/node_modules/web3-core-requestmanager/src/index.js:177:1
    at /usr/local/lib/node_modules/truffle/build/webpack:/packages/provider/wrapper.js:107:1
    at /Users/[USERNAME]/harmonauts/node_modules/@harmony-js/core/src/truffleProvider.ts:163:13
    at HttpProvider.callbackHandler (/Users/[USERNAME]/harmonauts/node_modules/@harmony-js/network/src/providers/http.ts:141:7)
    at /Users/[USERNAME]/harmonauts/node_modules/@harmony-js/network/src/providers/http.ts:82:30
    at processTicksAndRejections (node:internal/process/task_queues:94:5)
Truffle v5.1.58 (core: 5.1.58)
Node v15.11.0
```
MacOS Catalina 10.15.7

**Comment by ivorytowerdds** [comment]
Hi Chris,

Thanks for your question! Did you also change your `MAINNET_MNEMONIC` ?

**Comment by chriscrutt** [comment]
> Hi Chris,
> 
> Thanks for your question! Did you also change your `MAINNET_MNEMONIC` ?

yes sorry I edited above to say that @ivorytowerdds

**Comment by ivorytowerdds** [comment]
> > Hi Chris,
> > Thanks for your question! Did you also change your `MAINNET_MNEMONIC` ?
> 
> yes sorry I edited above to say that @ivorytowerdds

I need to check out that. The project is one year ago. Not sure whether there is any infrastructure changed since then
